### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Violenser** [MrZillaGold/VK2Discord#763]

**Comment by Violenser** [comment]
> Здравствуйте, помогите решить ошибку. При запуске скрипта высвечивается ошибка:
> 
> (node:8180) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time (Use `node --trace-warnings ...` to show where the warning was created) [VK2Discord] Запущен. [VK2Discord] Кластер #1 будет проверять новые записи с интервалом в 300 секунд. (node:8180) UnhandledPromiseRejectionWarning: ExecuteError: Code №100 - One of the parameters specified was missing or invalid at file:///C:/Users/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D1%8F/Desktop/Discord/node_modules/vk-io/lib/index.mjs:1670:73 at Array.map () at ParallelWorker.execute (file:///C:/Users/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D1%8F/Desktop/Discord/node_modules/vk-io/lib/index.mjs:1670:57) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) (node:8180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> 
> Я зелёный в этой теме и вообще не понимаю с чем связана эта ошибка
